# Generated by Django 5.2.6 on 2025-10-13 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='imports/')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VALIDATING', 'Validating'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('IMPORTING', 'Importing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('error_summary', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('column_name', models.CharField(blank=True, max_length=100, null=True)),
                ('error_type', models.CharField(choices=[('MISSING_COLUMN', 'Missing Required Column'), ('INVALID_FORMAT', 'Invalid Format'), ('DUPLICATE_VALUE', 'Duplicate Value'), ('FOREIGN_KEY_ERROR', 'Related Record Not Found'), ('VALIDATION_ERROR', 'Validation Error'), ('DATA_TYPE_ERROR', 'Data Type Error')], max_length=20)),
                ('error_message', models.TextField()),
                ('raw_value', models.TextField(blank=True, null=True)),
                ('suggested_value', models.TextField(blank=True, null=True)),
                ('data_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='data_import.dataimport')),
            ],
            options={
                'ordering': ['row_number', 'column_name'],
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, null=True)),
                ('data_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='data_import.dataimport')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('CUSTOMERS', 'Customers'), ('SUPPLIERS', 'Suppliers'), ('ITEMS', 'Items/Products'), ('INVENTORY', 'Initial Inventory'), ('CATEGORIES', 'Categories'), ('LOCATIONS', 'Locations'), ('USERS', 'Users'), ('SALES_ORDERS', 'Sales Orders'), ('INVOICES', 'Invoices'), ('PAYMENTS', 'Payments'), ('PURCHASE_ORDERS', 'Purchase Orders'), ('BILLS', 'Bills'), ('SUPPLIER_PAYMENTS', 'Supplier Payments'), ('ACCOUNTS', 'Accounts'), ('JOURNAL_ENTRIES', 'Journal Entries'), ('JOURNAL_ITEMS', 'Journal Items'), ('LEDGERS', 'Ledgers')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('required_columns', models.JSONField(help_text='List of required column names')),
                ('optional_columns', models.JSONField(default=list, help_text='List of optional column names')),
                ('column_mappings', models.JSONField(default=dict, help_text='Mapping of Excel columns to model fields')),
                ('validation_rules', models.JSONField(default=dict, help_text='Validation rules for each column')),
                ('sample_file', models.FileField(blank=True, null=True, upload_to='import_templates/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'template_type')},
            },
        ),
        migrations.AddField(
            model_name='dataimport',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='data_import.importtemplate'),
        ),
        migrations.CreateModel(
            name='ImportMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('column_mappings', models.JSONField(help_text="User's custom column mappings")),
                ('is_default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_import.importtemplate')),
            ],
            options={
                'unique_together': {('user', 'template', 'name')},
            },
        ),
    ]
